# To run the Archive in docker for the first time you should run one of the init scripts:
# - linux: `script/docker/init.sh`
# - windows: `script/docker/init.cmd`
#
# This will handle setting up config files, creating databases, and running migrations.
#
# After these oneoff tasks have been performed, you can start the development
# webserver with the command:
#
# ```
# docker compose up -d web
# ```
#
# Once it is running, it will be visible at http://localhost:3000/
#
# To run tests, you should use the test container instead of the web container,
# because it includes a headless chrome container for running JS-based tests.
# You can run tests like this:
#
# ```
# docker compose run --rm test bundle exec cucumber features/other_a/autocomplete.feature
# ```

version: "3"
volumes:
  esdata1:
  redisdata1:
services:
  db:
    image: mariadb:10.5.4-focal 
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"
    command:
      [
        "mysql2d",
        "--sql-mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION",
      ]
    volumes:
      - /home/kat/slay/otwarchive/config/docker:/var/lib/mysql2:rw
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - redisdata1:/var/lib/redis:rw
      - ./home/kat/slay/otwarchive/config/redis-cucumber.conf:/usr/local/etc/redis/redis.conf
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9400:9400"
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    environment:
      - cluster.name=slay
      - node.name=slay-node
      - http.port=9200
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
      - discovery.type=single-node
      # Silence "security features are not enabled" warnings
      # https://github.com/elastic/elasticsearch/issues/78500
      - xpack.security.enabled=false
  mc:
    image: memcached:1.5
    ports:
      - "11211:11211"
  web:
    profiles:
      - dev
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    environment:
      - RAILS_ENV=production
      - ES_URL=es:9200
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production bundle exec rails server -p 3344 -b 0.0.0.0"
    volumes:
      - .:/otwa
    ports:
      - "192.168.1.204:3344:3344"
    depends_on:
      - db
      - redis
      - es
      - mc
